### ISSUE TITLE
Set the title of the page dynamically

### ISSUE THREAD

**Issue by subhashb** [s-cork/HashRouting#11]
Currently, we can set page title by setting the `title` parameter of the `@routing.route`, but we can supply only items in `url_keys` for dynamic title construction. If the form is displaying an article, we would want to display its title instead of its `id`.

```
@routing.route('article', url_keys=['id'], title="Article-{id} | RoutingExample")
class ArticleForm(ArticleFormTemplate):
```

Is it possible to set the title of the page directly? We can then load the `article` object from DB and set the title manually in `__init__`.

**Comment by s-cork** [comment]
Sure. Currently the simplest way - and what I do in the dependency - is to use 

```python
from anvil.js.window import document

document.title = 'foo'
```

**Comment by subhashb** [comment]
> Sure. Currently the simplest way - and what I do in the dependency - is to use
> 
> ```python
> from anvil.js.window import document
> 
> document.title = 'foo'
> ```

Worked like a charm! Thanks! 👍
